### ISSUE TITLE
[SUGESTÃO] adicionar tutorial "Como fazer um roteador caseiro, seguro, com Raspberry e OpenWRT"

### ISSUE THREAD

**Issue by ElisonLima** [Alexemidio/PrivacyOpenSource#5]

**Comment by Alexemidio** [comment]
Ótima sugestão , assim que termina livro que estou escrevendo vou escreve sobre.

**Comment by ElisonLima** [comment]
Segue a lista de links que utilizei para conseguir fazer o meu.

Deixando só para registro:

1. https://www.makerhero.com/blog/openwrt-transforme-sua-raspberry-pi-em-um-roteador/
2. https://embarcados.com.br/openwrt-customizando-e-embarcando-na-raspberry-pi/#Configurando-a-placa-alvo-e-pacotes-para-o-OpenWRT
3. https://openwrt.org/toh/raspberry_pi_foundation/raspberry_pi
4. https://twitter.com/_DouglasEsteves/status/1125049452149059584
5. https://www.youtube.com/results?search_query=raspberry+openwrt
6. https://pt.slideshare.net/slideshow/monte-seu-roteador-seguro/143749432

**Comment by ElisonLima** [comment]
Mais algumas outras dicas:
- https://www.youtube.com/watch?v=lUzSsX4T4WQ
- https://www.youtube.com/watch?v=LbPg4-JKgtg
